// Dados do Teatro EAC — Paróquia de Santo Antônio
// Estrutura: PLAYS (peças) e CHARACTERS (personagens)

// av (avatar): { skin, hair (color+style), acc (accessory), mouth, eyes }
// skin: light|medium|tan|dark
// hair.style: short|long|bangs|bun|ponytail|gray-perm|slick|emo|bald|covered|doll
// acc: glasses|nerd-glasses|crown|tiara|bow|headband|sport-band|beard|mask|hood|veil|kerchief|pajama-cap|judge-wig|halo|suit-tie|priest-hat|apron-bow|null
// mouth: smile|sad|open|line|smirk
// eyes: open|closed|wink|glasses|shy

const CHARACTERS = {
  camila:        { name: 'Camila',        color: '#e0245e', traits: ['Adolescente', 'Aparece nas 3 peças'],
    av: { skin: 'light', hair: {color:'#5a3a1e', style:'long'}, acc: 'bow', mouth:'smile' } },
  joao:          { name: 'João',          color: '#4a9eda', traits: ['Adolescente', 'Aparece nas 3 peças', '"Dorminhoco"', 'Usa o pijama do EAC nos 3 dias'],
    av: { skin: 'medium', hair: {color:'#2b1c10', style:'short'}, acc: 'pajama-cap', mouth:'line', eyes:'closed' } },
  nina:          { name: 'Nina',          color: '#f5a4c8', traits: ['Adolescente', 'Aparece nas 3 peças', 'Grupo das Migas'],
    av: { skin: 'light', hair: {color:'#7a4a20', style:'long'}, acc: 'bow', mouth:'smirk' } },
  eugenio:       { name: 'Eugênio',       color: '#2c4d8f', traits: ['Adolescente', 'Aparece nas 3 peças', '"Nerd"', 'Usa suspensório nos 3 dias'],
    av: { skin: 'light', hair: {color:'#3a2416', style:'slick'}, acc: 'nerd-glasses', mouth:'smile' } },
  lorena:        { name: 'Lorena',        color: '#7a4dbd', traits: ['Adolescente', 'Aparece nas 3 peças', '"Acelerada"', 'Usa vestido de princesa'],
    av: { skin: 'light', hair: {color:'#c98b3d', style:'long'}, acc: 'tiara', mouth:'open' } },
  emanuel:       { name: 'Emanuel',       color: '#4a9d5f', traits: ['Adolescente', 'Aparece nas 3 peças', '"Emo"'],
    av: { skin: 'light', hair: {color:'#111', style:'emo'}, acc: null, mouth:'sad' } },
  paty:          { name: 'Paty',          color: '#d94b8f', traits: ['Adolescente', 'Aparece nas 3 peças', '"Patricinha"', 'Grupo das Migas'],
    av: { skin: 'light', hair: {color:'#e6c07a', style:'long'}, acc: 'bow', mouth:'smirk' } },
  remela:        { name: 'Remela',        color: '#a02f42', traits: ['Adolescente', 'Aparece nas 3 peças', '"Atleta"'],
    av: { skin: 'medium', hair: {color:'#1e1208', style:'short'}, acc: 'sport-band', mouth:'smile' } },
  britney:       { name: 'Britney',       color: '#7d1a3a', traits: ['Adolescente', 'Aparece nas 3 peças', '"Patricinha"', 'Grupo das Migas'],
    av: { skin: 'light', hair: {color:'#e8a4b8', style:'ponytail'}, acc: 'bow', mouth:'smirk' } },
  avelino:       { name: 'Avelino',       color: '#c33a2c', traits: ['Irmão mais velho dos adolescentes', 'Aparece nas 3 peças', 'Usa a blusa do EAC', 'Coordenador'],
    av: { skin: 'medium', hair: {color:'#2b1c10', style:'short'}, acc: null, mouth:'smile' } },
  kelly:         { name: 'Kelly',         color: '#5c3990', traits: ['Irmã mais velha dos adolescentes', 'Aparece nas 3 peças', 'Usa a blusa do EAC', 'Coordenadora'],
    av: { skin: 'light', hair: {color:'#3a2416', style:'bun'}, acc: null, mouth:'smile' } },
  angelo:        { name: 'Ângelo',        color: '#3a6b2c', traits: ['Pai de Eugênio', 'Aparece na 1ª peça'],
    av: { skin: 'light', hair: {color:'#5a4436', style:'slick'}, acc: 'glasses', mouth:'smile' } },
  jesus:         { name: 'Jesus',         color: '#1e4b7a', traits: ['2ª peça', '3ª peça'],
    av: { skin: 'medium', hair: {color:'#4a2b12', style:'long'}, acc: 'beard', mouth:'smile' } },
  juju:          { name: 'Juju',          color: '#4a9d5f', traits: ['Boneca', 'Aparece na 1ª e na 3ª peça'],
    av: { skin: 'light', hair: {color:'#c48a4e', style:'doll'}, acc: 'bow', mouth:'smile', eyes:'wink' } },
  julio:         { name: 'Júlio',         color: '#3a6b2c', traits: ['Pai de Emanuel'],
    av: { skin: 'medium', hair: {color:'#1e1208', style:'short'}, acc: 'beard', mouth:'open' } },
  'doutor-da-lei': { name: 'Doutor da lei', color: '#4a7a3a', traits: ['2ª peça'],
    av: { skin: 'medium', hair: {color:'#3a2416', style:'covered'}, acc: 'beard', mouth:'smirk' } },
  salete:        { name: 'Salete',        color: '#c33a2c', traits: ['Mãe de Camila', 'Aparece na 1ª e na 3ª peça'],
    av: { skin: 'light', hair: {color:'#5a3a1e', style:'bun'}, acc: null, mouth:'smile' } },
  'ladrao-1':    { name: 'Ladrão 1',      color: '#d97a2c', traits: ['2ª peça'],
    av: { skin: 'medium', hair: {color:'#1a1208', style:'short'}, acc: 'mask', mouth:'smirk' } },
  'ladrao-2':    { name: 'Ladrão 2',      color: '#c9a237', traits: ['2ª peça'],
    av: { skin: 'tan', hair: {color:'#1a1208', style:'short'}, acc: 'mask', mouth:'smirk' } },
  lazaro:        { name: 'Lázaro',        color: '#d97a2c', traits: ['3ª peça'],
    av: { skin: 'medium', hair: {color:'#3a2416', style:'covered'}, acc: 'beard', mouth:'line' } },
  marluce:       { name: 'Marluce',       color: '#e69128', traits: ['Babá de Nina'],
    av: { skin: 'medium', hair: {color:'#3a2416', style:'bun'}, acc: 'glasses', mouth:'open' } },
  marta:         { name: 'Marta',         color: '#d97a2c', traits: ['3ª peça'],
    av: { skin: 'light', hair: {color:'#5a3a1e', style:'covered'}, acc: 'kerchief', mouth:'sad' } },
  'joao-discipulo': { name: 'João (Discípulo)', color: '#c9a237', traits: ['3ª peça'],
    av: { skin: 'medium', hair: {color:'#4a2b12', style:'covered'}, acc: null, mouth:'smile' } },
  nice:          { name: 'Nice',          color: '#2b7a5a', traits: ['Mãe de Nina'],
    av: { skin: 'light', hair: {color:'#e6c07a', style:'ponytail'}, acc: 'glasses', mouth:'smirk' } },
  maria:         { name: 'Maria',         color: '#1e4b7a', traits: ['3ª peça'],
    av: { skin: 'light', hair: {color:'#4a2b12', style:'covered'}, acc: 'veil', mouth:'smile' } },
  sacerdote:     { name: 'Sacerdote',     color: '#4a6ba0', traits: ['2ª peça'],
    av: { skin: 'medium', hair: {color:'#5a5a5a', style:'covered'}, acc: 'priest-hat', mouth:'line' } },
  tome:          { name: 'Tomé (Discípulo)', color: '#4a6ba0', traits: ['3ª peça'],
    av: { skin: 'medium', hair: {color:'#3a2416', style:'covered'}, acc: 'beard', mouth:'sad' } },
  izabel:        { name: 'Izabel',        color: '#b19ccc', traits: ['Avó de João e Lorena', '1ª peça'],
    av: { skin: 'light', hair: {color:'#c4c4c4', style:'gray-perm'}, acc: 'glasses', mouth:'smile' } },
  'dona-estalagem': { name: 'Dona da estalagem', color: '#b19ccc', traits: ['2ª peça'],
    av: { skin: 'light', hair: {color:'#8a5a30', style:'bun'}, acc: 'apron-bow', mouth:'smile' } },
  homem:         { name: 'Homem',         color: '#808080', traits: ['2ª peça'],
    av: { skin: 'medium', hair: {color:'#3a2416', style:'short'}, acc: null, mouth:'sad', eyes:'closed' } },
  pedro:         { name: 'Pedro (Discípulo)', color: '#606060', traits: ['3ª peça'],
    av: { skin: 'medium', hair: {color:'#5a4436', style:'covered'}, acc: 'beard', mouth:'line' } },
  samaritano:    { name: 'Samaritano',    color: '#8a7a2a', traits: ['2ª peça'],
    av: { skin: 'medium', hair: {color:'#3a2416', style:'covered'}, acc: 'beard', mouth:'smile' } },
  mensageiro:    { name: 'Mensageiro',    color: '#8a7a2a', traits: ['3ª peça'],
    av: { skin: 'light', hair: {color:'#4a2b12', style:'short'}, acc: null, mouth:'open' } },
  levita:        { name: 'Levita',        color: '#a05a2c', traits: ['2ª peça'],
    av: { skin: 'medium', hair: {color:'#3a2416', style:'covered'}, acc: null, mouth:'open' } },
  todos:         { name: 'Todos',         color: '#555',   traits: ['Fala em conjunto'],
    av: { skin: 'light', hair: {color:'#4a2b12', style:'short'}, acc: null, mouth:'smile' } },
  meninos:       { name: 'Meninos',       color: '#4a9eda', traits: ['Coro dos meninos — 3ª peça'],
    av: { skin: 'medium', hair: {color:'#2b1c10', style:'short'}, acc: null, mouth:'smile' } },
  meninas:       { name: 'Meninas',       color: '#f5a4c8', traits: ['Coro das meninas — 3ª peça'],
    av: { skin: 'light', hair: {color:'#c48a4e', style:'long'}, acc: 'bow', mouth:'smile' } },
  juiz:          { name: 'Juiz(a)',       color: '#333',   traits: ['Conduz o julgamento — Júri do Bruno'],
    av: { skin: 'light', hair: {color:'#e8e8e8', style:'covered'}, acc: 'judge-wig', mouth:'line' } },
  bruno:         { name: 'Bruno',         color: '#4a7a4a', traits: ['O réu — Júri do Bruno', 'Postura retraída, cabeça baixa'],
    av: { skin: 'medium', hair: {color:'#3a2416', style:'covered'}, acc: 'hood', mouth:'sad', eyes:'shy' } },
  'acusacao-1':  { name: 'Acusação 1',    color: '#a02f42', traits: ['Júri do Bruno'],
    av: { skin: 'light', hair: {color:'#3a2416', style:'slick'}, acc: 'suit-tie', mouth:'smirk' } },
  'acusacao-2':  { name: 'Acusação 2',    color: '#a02f42', traits: ['Júri do Bruno'],
    av: { skin: 'light', hair: {color:'#5a3a1e', style:'ponytail'}, acc: 'suit-tie', mouth:'smirk' } },
  'defesa-1':    { name: 'Defesa 1',      color: '#2b7a5a', traits: ['Júri do Bruno'],
    av: { skin: 'medium', hair: {color:'#2b1c10', style:'short'}, acc: 'suit-tie', mouth:'smile' } },
  'defesa-2':    { name: 'Defesa 2',      color: '#2b7a5a', traits: ['Júri do Bruno'],
    av: { skin: 'light', hair: {color:'#c48a4e', style:'long'}, acc: 'suit-tie', mouth:'smile' } },
  mirabel:       { name: 'Mirabel',       color: '#e69128', traits: ['Testemunha — Júri do Bruno'],
    av: { skin: 'medium', hair: {color:'#2b1c10', style:'bangs'}, acc: 'glasses', mouth:'smile' } },
};

// -----------------------------------------------------------------------------
// Helpers de construção
const s = (text) => ({ type: 'stage', text });
const l = (character, text) => ({ type: 'line', character, text });
const n = (text) => ({ type: 'narration', text });

// -----------------------------------------------------------------------------
const PLAYS = [
  // =========================================================================
  // 1ª PEÇA
  // =========================================================================
  {
    id: '1',
    slug: 'pre-conceito',
    number: '1ª Peça',
    title: 'Todo começo gera sempre um "Pré-conceito"',
    synopsis: 'Cada adolescente sai de casa rumo ao EAC com seu jeito bem particular. Ao se encontrarem, os julgamentos aparecem — até entenderem que as diferenças são o que os une.',
    parts: [
      {
        title: '1ª PARTE',
        scenes: [
          {
            title: '1ª CENA — Camila e Juju',
            setting: 'Abrem-se as cortinas e aparece Camila em seu quarto tentando fechar sua mala.',
            beats: [
              l('camila', 'Mala? OK! Travesseiro? Ok! Sandálias? Ok!! Será que estou esquecendo alguma coisa, Juju?'),
              s('Fala pra boneca encostada na cama e a boneca balança a cabeça confirmando que sim e inicia um áudio com o seu pensamento.'),
              l('juju', 'Claro que tá! Tu tá me esquecendo, mulherzinha, ó eu aqui!'),
              l('camila', 'AAAHH, Juju, mas é claro! Como eu poderia te deixar…'),
              s('Caminhando em direção a Juju, Juju começa a sorrir, Camila passa direto e pega a bombinha de asma.'),
              l('camila', 'Ai, Juju, você sempre salvando a minha vida.'),
              s('Juju faz cara de raiva, pois achava que era ela que ela ia buscar e inicia mais um áudio.'),
              l('juju', 'AIKI MENINA CHATA! Eu pensava que fosse me levar! Aff'),
              l('camila', 'Sabe, Juju, estou tão ansiosa pra ir pro encontro, bem que você poderia ir, não é?'),
              s('Juju balança a cabeça confirmando e iniciam mais um áudio.'),
              l('juju', 'Me leva, abestalhada! Nunca te pedi nada!'),
              l('camila', 'Não é não, brincadeirinha! Você é uma boneca e o EAC é para adolescentes, mas prometo que quando chegar te conto tudo! Bonequinha linda.'),
              s('Aperta as bochechas dela. Juju faz bico de raiva e inicia mais um áudio.'),
              l('juju', 'Do que adianta ser essa bonequinha linda se eu não posso sair por aí distribuindo essa beleza suprema? Eu não sou obrigada a ficar em casa. Aliás, eu não sou obrigada a nada.'),
              s('Entra a mãe de Camila.'),
              l('salete', 'Camila, minha filha, você já esta pronta? Venha lanchar se não você se atrasa filha!'),
              l('camila', 'Tô sim, mãe! Aí, mãe, tô tão empolgada pro EAC!'),
              l('salete', 'E eu num sei, menina! Tu falou em alguma coisa esta semana a não ser do EAC? Até eu estou ansiosa já e se brincar até a Juju, não é, Juju?'),
              s('Juju faz bico ignorando e inicia mais um áudio.'),
              l('juju', 'Lá vem a ôta!'),
              l('salete', 'Vamos tomar café, teu pai já está terminando o banho pra gente ir!'),
              l('camila', 'Mas tá legal essa roupa, mãe?'),
              l('salete', 'Aí, filha, tá linda! Você tá como diz seu pai, mais linda que uma boneca!'),
              s('Juju cruza os braços incomodada e inicia mais um áudio.'),
              l('juju', 'ME RESPEITA! Minha beleza é incomparável! Eu poderia ser até uma boneca da Gisele Bundchen!'),
              l('camila', 'Aí, mãe, num me mata de vergonha né?'),
              l('salete', 'Que orgulho de você, filha! Entrando nos caminhos de Deus e estou mais feliz ainda de ver que você está feliz por isso, mas vamos que se não mainha já começa a chorar aqui.'),
              s('Começa a chorar bem engraçado e Camila a puxa pela mão saindo do quarto.'),
              l('camila', 'Owwn, mãe!!! Vem, vamos lanchar, vamos!'),
              s('As duas saem de cena. Juju levanta, vai até a porta para ver se vem alguém e volta a cama.'),
              l('juju', 'E dizem que vida de boneca é fácil! Tá vendo só? Eu queria ir pro EAC também.'),
              s('Começa a chorar.'),
              l('juju', 'Tem nada não, bixinha! Eu vou aproveitar e vou dormir na cama esse fim de semana todinho, porque já estou com a coluna torta de passar a vida nessa posição neste chão duro, ow chão duro!'),
              s('Fecham as cortinas.'),
            ],
          },
          {
            title: '2ª CENA — Nina, Marluce e Nice',
            setting: 'Abre as cortinas e dá no quarto de Nina dormindo na cama enquanto Marluce está cantando.',
            beats: [
              l('marluce', 'TÔ NAMORANDO UM X TUDOOO, 99% QUEIJO COM BACON, MAS AQUELE 1% É DE PRESUNTOO. AQUELE 1% É DE PRESUNTO, SALGADO E ELAS GOSTAMMM, SÓ UM PORCEENTOOO…'),
              s('Marluce vai parando de cantar e vai indo em direção a Nina, acordá-la, puxando-a pelo pé.'),
              l('marluce', 'Nina! Nina! Ninaaa, mulherzinhaaaa! Ow bixinha do sono pesado, parece uma péda a criatura. Nina? Nina, mulher, se tua mãe entrar nesse quarto e tu ainda tiver nessa cama ela te puxa a alma, mulherzinha! Nina? Nina? Nina, ou menininha preguiçosa essa! Mulher… oía a hora, mulherzinha, tu tem que ajeitar teus troços pra ir pro E… pro E… é o que mermo esse negócio que Nina vai? Sei não, só sei que essa MI-NI-NA dá um trabaí pra ÇALEVANTAR dessa cama…'),
              s('GRITA.'),
              l('marluce', 'NINNAAAAAAAAAA, MULHERRRR, ÇALEVANTA, CRIATURA!!!'),
              l('nina', 'AAAAAAAHHH! O que é isso, Marluce? Tá doida é?'),
              l('marluce', 'Mulher… eu tarra te acordando!'),
              l('nina', 'E não podia só chamar meu nome, ou puxar meu pé, precisa desse show todinho?'),
              l('marluce', 'Mulher, se eu puxasse mais tua perna vinha na minha mão!'),
              l('nina', 'E hoje eu não tenho aula, porque você me acordou?'),
              l('marluce', 'Mulherzinha, e tu num vai praquele negócio de É.'),
              l('nina', 'Negócio de É? Que negócio de é?'),
              l('marluce', 'Ow, mulher, cumprica minha cabeça não, só sei que se tua mãe entrar ali pela quela porta e tu ainda tiver aí na cama, eu tenho até medo!'),
              s('Nice, a mãe de Nina, entra no quarto dando um grito e Marluce cai da cama do susto e derruba os óculos.'),
              l('nice', 'NINNAAAAAAAAAAAAAA!!!'),
              l('marluce', 'Valha mim DEUS! Eu quase caí!'),
              l('nice', 'I don\'t believe que você ainda está nesta cama, Nina! Você já viu que horas são, você nem a mala ajeitou pra ir pro EAC e o motorista está lá fora a sua espera!'),
              s('Marluce fica de quatro procurando os óculos.'),
              l('marluce', 'Meu óculos! Ninguém sai!'),
              l('nice', 'Marluce, I DON\'T BELIEVE que eu mando tu chamar esta GIRL e tu fica aí brincando, é?'),
              l('marluce', 'Mai eu sô mole mermo!'),
              l('nina', 'Ah, mãe e é hoje isto é? Que saco, eu já fui pro inglês, quero mais aula hoje não!'),
              l('nice', 'Que aula, Nina? HELOOO? Wake-up, filha! Isso não é aula de nada não, ou é? Acho que pode ser alguma aula de religião, por via das dúvidas, comprei esse caderno BEAUTIFUL aqui! Agora já pro banho que eu vou ligar para Misraine dizendo que minha filhinha vai pro EACêÊÊ!'),
              l('nina', 'Tá mãeee…'),
              s('Sai arrastando o lençol.'),
              l('nice', 'Enquanto isso Marluce vai arrumando sua mala!'),
              s('Nice e Nina saem da cena.'),
              l('marluce', 'Maí eu sô mole mermo, sabia que ia sobrar pra mim! O que é que eu sou sem Jesus? Nada! Nada! Nada!'),
              s('Fecham as cortinas.'),
            ],
          },
          {
            title: '3ª CENA — João, Lorena e a avó Izabel',
            setting: 'Abrem-se as cortinas na casa dos primos João e Lorena. A avó deles está sentada assistindo a novela.',
            beats: [
              l('izabel', 'Mai que televisão baixa é essa? Ninguém escuta nada que se passa nessa novela.'),
              s('Ela pega o controle e aumenta o volume da tv no máximo.'),
              l('izabel', 'Pronto, agora sim, agora eu escuto! Nem tá muito baixo, nem tá muito alto.'),
              s('João vem se arrastando, pega o controle e baixa o volume da TV.'),
              l('joao', 'Ou, vó, eu não tô achando minha escova de dentes não.'),
              l('izabel', 'É o que João?'),
              s('Entra Lorena do outro lado da vó.'),
              l('lorena', 'Vó, vó, vó! Tô pronta já, mala, roupas, cobertor, travesseiros, shampoo…'),
              l('joao', 'Vó, cadê minha escova?'),
              l('izabel', 'É o que Mininu?'),
              l('lorena', 'Nacredito não João, que nós vamos se atrasar por conta da tua lerdeza não, faz mais de duas horas que eu estou pronta, isso pode vó?'),
              l('izabel', 'É o que, Lorena?'),
              s('João e Lorena falam ao mesmo tempo.'),
              l('joao', 'Eu não tô achando minha escova.'),
              l('lorena', 'O João perdeu a escova dele!'),
              l('izabel', 'Eitaaa, precisa gritar não, num sô môca não! Ow, minina fale mais devagar vá, e ou mininu, fala mais rápido, fale! Ow, João, você já procurou no banheiro, já?'),
              l('joao', 'Eita, ó! Ainda não! Valeu vó, vou lá.'),
              s('Sai se arrastando.'),
              l('lorena', 'Vó, vou pegar minha mala pra gente ir pro EAC!'),
              l('izabel', 'Eu nunca vi dois primos tão diferentes, desse lado eu sou agoniadinha e desse outro eu sou uma lerdeza.'),
              l('joao', 'Pronto, vó!'),
              l('lorena', 'Pronto, pronto, pronto, vó, vamos!'),
              s('Puxa o braço da vó com tudo.'),
              l('izabel', 'Eita, Lorenaaa, tu desloca meu braço, minina!'),
              s('Saem de cena. Fecham-se as cortinas.'),
            ],
          },
          {
            title: '4ª CENA — Eugênio e Ângelo',
            setting: 'Abrem as cortinas e dá no quarto de Eugênio estudando.',
            beats: [
              l('eugenio', 'Aqui é simples, essa equação de segundo grau tá dada, é só calcular o Delta. Pronto, isso, delta deu 3.240,000 então a raiz de 3.2400,00, é… humm… ah, 1800! Agora é só jogar na fórmula de bhaskara e descobrir x´ e x´´. AAAh, papai! Eu sou fooooo…rmidável!'),
              s('Entra o pai de Eugênio.'),
              l('angelo', 'Ow meu filho, você ainda está estudando? Qual a probabilidade de você ter ajeitado suas malas, Eugênio?'),
              l('eugenio', 'A probabilidade é de 100%, meu pai. Calculei todo meu tempo antes de ir para o EAC e me sobra 5 minutos ainda pra uma leitura! HEHEHEHE'),
              l('angelo', 'Eugênio meu filho, só que eu calculei todo o meu trajeto até o Ipuarana e coloquei a probabilidade de 70% encontrarmos um engarrafamento e estou com -5min do meu tempo, ou seja, atrasado!'),
              l('eugenio', 'Sério, Pai? Mas isso foi a que velocidade média? HEHEHE'),
              l('angelo', 'A velocidade suficiente para chegar em paz em qualquer lugar, devagar! Agora vamos!'),
              s('O pai pega a mochila do filho.'),
              l('angelo', 'Aqui tem chumbo é?'),
              l('eugenio', 'HEHEHE não, pai, é toda a minha saga de Harry Potter, quero ler cada livro antes de dormir. HEHEHE'),
              l('angelo', 'Ai, ai, eu não sei a quem esse menino puxou? HEHEHE Vamos, Eugenio, vamos!'),
              l('eugenio', 'Ow, pai, será que não dá tempo mesmo eu resolver só mais esta equação aqui, tá faltando pouquinho, deixa, vai, deixa!'),
              l('angelo', 'Não, filho, vamos.'),
              l('eugenio', 'Ow, Paaaaaai, deixa vai!!'),
              l('angelo', 'Não, vamos.'),
              l('eugenio', 'Own, papai, assim num vale!!'),
              s('Inicia o instrumental da música da metralhadora e Eugênio começa a cantar.'),
              l('eugenio', 'Lápis apontando, cérebro fervendo, querendo estudar e papai interrompeeendooooo… PEGA A CALCULADORA HEHEHEHE TRA TRA TRA TRA TRA VALOR DO "X" VOU ENCONTRAR TRA TRA TRA'),
              l('angelo', 'TRA TRA TRA TRA TRA TRA ME DÁ ISSO AQUI'),
              s('Pegando a calculadora.'),
              l('angelo', 'E PASSA PRA LÁ, LÁ, LÁ E ACELERAÊ!'),
              s('Fecham as cortinas.'),
            ],
          },
          {
            title: '5ª CENA — Emanuel e Júlio',
            setting: 'Entra em cena Emanuel se esfregando nas paredes.',
            beats: [
              l('emanuel', 'Eu vou te esperar, pra onde quer que eu vá! Pra onde quer que eu vá, te levo comigo! Ow, Teddy, eu tô indo pro EAC, mai meu pai nem deixou eu txi levar, eu sei que tu tá tliste, que droga, que droga, que droga! Pronto! Respira! Tô calmo, tô calmo, calmo, calminho…. Que droga! Que droga! Que droga!!!'),
              s('Entra o pai de Emanuel de surpresa.'),
              l('julio', 'Que presepada é essa, Emonoel?'),
              l('emanuel', 'Ai, pai, que susto! Sabe, pai? Eu tô tliste.'),
              l('julio', 'TU TÁ OQ, MENINO?'),
              l('emanuel', 'Tliste…Tlistinho.'),
              l('julio', 'MAR DEIXA DE TUAS MARMOTA!! Eu nacredito que tu tá com esse urso na mão ainda não, Emonoel?'),
              l('emanuel', 'Ai, pai, eu tô!'),
              l('julio', 'TU TÁ OQ, MENINO?'),
              l('emanuel', 'Tliste…Tlistinho.'),
              l('julio', 'MAR DEIXA DE DUAS PRESEPADA! E pode ir butano esse danado aí, pode logo!'),
              l('emanuel', 'Ai, pai, eu queria levar ele!'),
              l('julio', 'Tá doido, é, Emanuel? Você saiu de si, foi?'),
              l('emanuel', 'Ai, pai…'),
              l('julio', 'Faleee direito que você num tá com dor não pra tá o tempo todo, ai, ai, ai!'),
              l('emanuel', 'Aiiii, pá…'),
              l('julio', 'Eu vou levando logo essa mala pra num ter nem perigo de tu botar esse urso aqui dentro! E tu cuida que tu sabe que eu não gosto de atraso não!'),
              l('emanuel', 'Ai, paiii, precisa disso? Eu num preciso de mala pra levar ele, neh, Teddy?'),
              s('Cochicha no ouvido de Teddy. Entra o pai.'),
              l('julio', 'Que presepada é essa, Emanuel? Tu ainda num tomou rumo, minino?'),
              l('emanuel', 'Ai, pai, que susto! Desse jeito eu vô morrer do coração.'),
              l('julio', 'Olhe, Emanuel, olhe a hora!'),
              l('emanuel', 'Ai, pai, que agonia! Tô todo me tremendo, chega tá me dando uma tlisteza…tô tliste, tlistinho.'),
              l('julio', 'Olhe, eu vou pro carro, mas eu só buzino uma vez viu?'),
              s('O pai sai de cena.'),
              l('emanuel', 'Ai, num vejo a hora chegar nesse EAC pra ver como é esse negócio.'),
              s('Som de buzina.'),
              l('emanuel', 'Eita, meu pai! Ai pai, já vou!'),
              s('Sai correndo com medo. Saem de cena. Fecham as cortinas.'),
            ],
          },
        ],
      },
      {
        title: '2ª PARTE — A chegada ao EAC',
        scenes: [
          {
            title: 'Chegada dos adolescentes',
            setting: 'A cena se passa na parte de baixo do palco, as patricinhas vão entrando aos poucos e fazendo comentários com todos que entram em cena.',
            beats: [
              l('paty', 'Não acredito que fui a primeira a chegar? OH MY GOD!! Não acredito que vou pagar esse mico? Aí, mãe e pai eu disse que dava tempo ainda eu escovar meus cabelos. E agora, se alguém chegar e me ver que fui a primeira? Mas eu não fui a primeira mesmo, eu não sou obrigada a nada, a nada! Vou me esconder.'),
              s('Vai para atrás da cortina. Entra Remela.'),
              l('remela', 'Brotheeer? Quer dizer que eu fui o primeiro a chegar? U-HU! Mermão, chega batendo (interage com um adolescente) sou o campeão! Reeeh! O 1º lugar é teu Remela! Tá tranquilo, tá favorável. Tá tranquilo, tá favorável.'),
              s('Entra Britney.'),
              l('britney', 'Olá, olá, olá, deixa eu ver essas carinhas aqui, hum, conheço, conheço, UÓ! Me segue no insta, ah, esse também!'),
              l('remela', 'Bri-bri!!!!!'),
              l('britney', 'Remela? MIGO, SEU LOKOOO! Não acredito que você vai fazer o EAC? SEJA MENOS IMITÃO!'),
              l('remela', 'E tu acha que eu ia perder de ser do primeiro EAC de Santo Antônio, acha? Acha?'),
              l('britney', 'E só chegou tu foi? Oxi, a Paty me mandou um whats dizendo que já estava chegando.'),
              l('remela', 'Mas ela perdeu e advinha quem ganhou? EU! EU! EU! Fui o primeiro a chegar.'),
              s('Pulando ele pisa no pé de Paty atrás da cortina.'),
              l('paty', 'Ai, meu péééé, Remelaaaa!'),
              l('britney', 'Paty, MIGA SUA LOKAAA, você está atrás da cortina? SEJA MENOS SECRETA!!'),
              l('paty', 'Surpresaaaa! Estava só aguardando vocês, CLARO, pra fazer uma surpresinha! Mas o pateta do Remela me atrapalhou, argh!'),
              s('Entra Nina.'),
              l('britney', 'PARAAA TUDO! AQUILO ALI É A NINA GOTEMFELD?'),
              l('paty', 'A própria!'),
              l('britney', 'AAAAAAH! MIGAAAASS!'),
              l('paty', 'AAAAAAH! MIGAAAASS!'),
              l('nina', 'MIGASSSS, SUAS LOKAAAS! QUE LOOK ARRAZADORES SÃO ESSES, HEIN? ATÉ PARECE COM O MEU! SEJAM MENOS GÊMEAS! Ufa que encontrei alguém conhecido nesse curso.'),
              l('remela', 'Curso? E é pra estudar é? Pois se for pra estudar eu vou é embora!'),
              l('britney', 'Stop, Remela!'),
              l('paty', 'Ow, migos seus lokos, né curso não! Sejam mais religiosos! Na verdade, o EAC é um encontro que acontece depois da 1ª Eucaristia e antes da Crisma, tem uma caminhada a seguir, MIGAS! Eu vim porque meu pai disse que eu teria que ter os 3!'),
              l('britney', 'LACRÔ, MIGA!'),
              l('nina', 'Mas pelo menos a gente tá junto, neh? Pode até ser perda de tempo, mas com certeza a gente vai se divertir, Mooooitoo! Falando em diversão, quem é aquela estranha que vem entrando ali, hein?'),
              s('Lorena vem entrando em cena.'),
              l('paty', 'Gentemm!! Que roupa é essa????? Ela só pode tá com a roupa da vó.'),
              l('britney', 'PAAARA TUDOO, BRASILLL!!! Ainda se usam essas meias?'),
              s('Todos riem.'),
              l('lorena', 'Ain que lindo, estou sendo recebida com alegria, oww, não precisava. Prazer, Lorena, prazer, prazer…'),
              s('Sai abraçando cada um bem rápido.'),
              l('paty', 'MIGA, SUA LOKA! SEJA MAIS RESPIRATÓRIA! Respira!'),
              l('nina', 'Eu tô vendo que o povo desse curso não bate muito bem da bola não!'),
              l('remela', 'Falem a verdade, a gente veio estudar foi?'),
              l('britney', 'REEMEELLAAA, STOP!'),
              l('paty', 'REEMEELLAAA, STOP!'),
              l('lorena', 'Ah meu deus, esqueci meu primo, eu tô vendo que ele ficou para trás, mas também, eu nunca consigo acompanhar ele, não sei porque, e é porque saímos igualzinho de casa, moramos com minha vó!'),
              l('remela', 'Nossa, até eu cansei agora! E quem é seu primo?'),
              s('Entra João o preguiçoso se arrastando.'),
              l('joao', 'Sou eu, o JOÃÃÃÃ… ÃÃÃOOO…'),
              s('E vem andando bem devagarzinho.'),
              l('remela', 'Minha tartaruga é mais rápida que esse cara.'),
              l('lorena', 'João, mininu, anda, tu num sabe que tem horário pra começar as coisas, se perdesse foi? Tu num deixou a mala igualzinho comigo, porque tu não me acompanhou, heim, menino?'),
              l('joao', 'Pra te acompanhar só se eu visse numa Ferrari. Agora cadê as cadeiras daqui, quero sentar…'),
              s('Vem entrando o Nerd.'),
              l('nina', 'Migaaaasss, mas aquilo ali não é o EUGÊNIO não?'),
              l('britney', 'O própriooo!'),
              l('nina', 'Com a mesma cara de Nerd de sempre!'),
              l('paty', 'E ele ainda vem lendo, é?'),
              s('Eugênio vem lendo em direção a alguma adolescente como se fosse bater nela.'),
              l('todos', 'OLHAAA A MENINAAAAA!!'),
              l('eugenio', 'Desculpa, desculpa! É que me distrai neste capítulo, ele é mega máximo, você já leu este livro? Da próxima vez que entrar vou calcular quantos passos devo dá até a frente sem precisar bater em ninguém.'),
              l('nina', 'Migo, seu loko! Seja mais enxergativo! Olha prus cantos!'),
              s('Entra o Emanuel com o urso escondido embaixo da camisa.'),
              l('britney', 'PARAA TUDOOO! O QUE É ISSO, BRASIL??'),
              l('emanuel', 'Faz silêncio, Teddy, ninguém pode perceber que você está aqui! Ai, Teddy, não se mexe!'),
              s('Teddy cai da camisa dele e todos começam a rir.'),
              l('nina', 'Ele trouxe um urso??? Migo, seu loko, seja menos criança! Kkkkkkkkk'),
              l('emanuel', 'Ai, Teddy, não era pra vc ter saído assim na frente de todos!'),
              l('lorena', 'Ow, o bichinho, venha pra cá, mininu, ligue com esse povo não, e seu ursinho é lindo, eu tenho um parecido com esse também, onde tu comprou? Ou foi tu que ganhou? O meu foi eu que ganhei!'),
              l('paty', 'Migasss, quem é aquela que vem ali?'),
              s('Entra Camila com a bíblia e um terço na mão e acenando pra todo mundo.'),
              l('britney', 'Miga, sua loka, seja menos crente!'),
              s('Todos riem.'),
              l('camila', 'Oláá!!'),
              s('Dá um sorriso pra eles. Vem entrando Avelino e Kelly, os coordenadores de grupo.'),
              l('avelino', 'Olá pessoal!'),
              l('kelly', 'Olá pessoal!'),
              l('avelino', 'Acho que já chegaram todos os adolescentes, não é? Então vamos sentando porque o encontro já vai começar.'),
              s('Todos sobem no palco. Quando todos estiverem sentados a cortina se abre.'),
            ],
          },
        ],
      },
      {
        title: '3ª PARTE — A reunião no EAC',
        scenes: [
          {
            title: 'A palavra sobre o preconceito',
            setting: 'A cena se passa numa sala preparada para uma reunião, tem altar, as cadeiras em círculo e Kelly está sentada fazendo uma oração. Avelino entra e começa a reunião.',
            beats: [
              l('avelino', 'Bom dia, pessoal! Hoje nós vamos começar uma nova caminhada, a caminhada EAC.'),
              s('Avelino faz uma breve reflexão sobre as dificuldades da caminhada, os preconceitos e a importância de todos no grupo.'),
              l('kelly', 'E para completar o que Avelino disse, eu vou ler aqui uma palavra que Jesus deixou pra nós, deixando claro que todos nós somos importantes independentemente de como somos.'),
              s('Kelly lê I Co 12, 14-23.'),
              l('kelly', 'Alguém quer comentar alguma coisa?'),
              l('lorena', 'Eu gostaria de falar só um tiquinho, eu achei tão legal quando cheguei aqui e vi tanta gente diferente, isso quer dizer que não precisamos ser todos iguais pra seguir a Jesus.'),
              l('emanuel', 'Owww, Teddy e eu vamos nos emocionar, porque aqui a gente se sentiu tão acolhido, num foi, Teddy?'),
              l('joao', 'Me deu até mais coragem agora!'),
              l('eugenio', 'Eu adoro biologia e vejo que cada parte do corpo é essencial e fazendo uma metáfora com nós, vejo o quanto vocês são importantes para o meu crescimento.'),
              l('camila', 'Isso! Isso! Sozinhos não conseguimos nada, e que preconceitos só vão nos atrasar e nos distanciar de Deus. Eu estou muito feliz em estar participando deste encontro e ver que tem adolescentes bem diferentes de mim, porque assim eu vou aprender coisas novas e vou poder passar coisas novas.'),
              l('britney', 'Ai Migasss! Isso é tão verdade!'),
              l('nina', 'Eu quero aprender com as diferenças, eu quero aprender com vocês.'),
              s('Camila vai até Nina e dá um abraço e assim cada um vai procurando um e ir abraçando. Toca a música "Amigos pela fé" (Anjos de Resgate) e todos se abraçam em círculo emocionados.'),
            ],
          },
        ],
      },
    ],
  },

  // =========================================================================
  // 2ª PEÇA
  // =========================================================================
  {
    id: '2',
    slug: 'bom-samaritano',
    number: '2ª Peça',
    title: 'O Bom Samaritano',
    synopsis: 'Camila torce o pé e cada um dos adolescentes tenta ajudar do seu jeito. A partir do gesto, os coordenadores contam a parábola do Bom Samaritano.',
    parts: [
      {
        title: '1ª PARTE — O socorro',
        scenes: [
          {
            title: 'Camila se machuca',
            setting: 'Camila entra em cena com o pé machucado junto com Lorena e João.',
            beats: [
              l('camila', 'Ai, ai, ai, meu pé! Eu torci ele enquanto dançava, Lorena, será que quebrei? Tá doendo muito!'),
              l('joao', 'Calma, Camilinha, vai passar logo, fica assim não.'),
              l('lorena', 'Calma, calma, calma, não tem pra que vexame. Vamos ter calma! Eu mesma, ó, tô muito calma, eu tô calma…'),
              s('Muito agoniada, começa a gritar.'),
              l('lorena', 'SOCORRO!! SOCORRO!!! Corre, João, mininu, ver se tu chama alguém.'),
              l('camila', 'Ai que susto, Lorena!'),
              l('joao', 'Ai que susto, Lorena!'),
              l('lorena', 'Corre, João! Corre!'),
              l('joao', 'Tá, eu vou correr atrás de alguém, espera que volto num instante.'),
              s('Sai correndo bem devagarzinho.'),
              l('camila', 'Ai como dói, como dói!'),
              l('lorena', 'AIIIIINN, quer que eu te abane? Eu te abano!'),
              s('Entra em cena Emanuel e Eugênio.'),
              l('eugenio', 'Nossa, Emanuel, ali é a Camila no chão?'),
              l('lorena', 'Acoooodee a gente aqui, acode!'),
              l('emanuel', 'Ai, Eugênio, é sim! Vamos correr.'),
              s('Derruba Teddy.'),
              l('eugenio', 'O que houve?'),
              l('camila', 'Acho que quebrei meu pé, não tô conseguindo me levantar, tá doendo!'),
              l('emanuel', 'Ai, Camila, tá vendo! Mas calminha, tá?'),
              l('lorena', 'Eu disse a ela, o segredo é ter calma que tudo se resolve, eu mesma estou aqui calminha.'),
              s('Tremendo já de nervosa.'),
              l('eugenio', 'Você tá tremendo, Lorena?'),
              l('lorena', 'Não, eu tô calma, muito calma, eu tô…'),
              s('Desmaia.'),
              l('todos', 'AI MEU DEUS!!'),
              l('camila', 'E agora gente, precisamos ajudar a Lorena também.'),
              l('emanuel', 'Deixa comigo, eu vou levar ela nos braços…'),
              s('Emanuel tenta pôr ela nos braços.'),
              l('emanuel', 'Aaaii… aiii… só mais um esforcinho… aiii… Ai, Emanuel, como tu é fraco.'),
              l('eugenio', 'Mas, Emanuel, podemos dividir o peso dela por dois e assim eu lhe ajudando podemos levá-la até outro lugar!'),
              s('Eugênio pega nos braços e Emanuel nas pernas de Lorena. Entram as MIGAS.'),
              l('nina', 'Migasss, que brincadeira é aquela ali?'),
              l('britney', 'Para tudo, Brasil! Não acredito que eles estão brincando não!'),
              l('paty', 'Hellooo, como a Lorena se passa!'),
              l('nina', 'Migaaasss, a Camila também tá ali, eu acho que aconteceu alguma coisa, vamos ajudar!'),
              l('paty', 'O que houve, meninos?'),
              l('emanuel', 'Primeiro a Camila machucou o pé!'),
              s('Solta as pernas de Lorena.'),
              l('eugenio', 'Depois a Lorena desmaiou!'),
              s('Solta os braços de Lorena.'),
              l('britney', 'E agora vocês quebraram ela toda, jogando assim!'),
              l('emanuel', 'Xiiii, foi mal!'),
              l('eugenio', 'Xiiii, foi mal!'),
              l('nina', 'Ow, Camila, deixa eu ver teu pé, dói muito é?'),
              l('camila', 'Muito, Nina!'),
              l('paty', 'Vamos chamar alguém.'),
              l('camila', 'O João já foi.'),
              l('britney', 'Mas ele só vai voltar amanhã, pode ter certeza!'),
              l('paty', 'Olha o Remela ali!'),
              l('britney', 'REMEEELAAAA, COME HERE!'),
              l('paty', 'REMEEELAAAA, COME HERE!'),
              l('remela', 'Achei que já iam mandar eu parar, eu nem tava fazendo nada… Mas, o que houve com a Lorena? O que foi Camila?'),
              l('britney', 'Resumindo, elas passaram mal! Stop!'),
              l('paty', 'Precisamos da sua força, Remela, para levar ela daqui.'),
              l('remela', 'REEEH, é o Remelinha na área! Todo fortão, todo musculoso, todo poderoso!'),
              l('todos', 'REMELAA, STOP!'),
              s('Remela pega Lorena no colo. Lorena começa a tornar.'),
              l('remela', 'Ela tá acordando já!'),
              l('lorena', 'Tô calma, hein? Calma, calminha!'),
              s('Entram os coordenadores.'),
              l('avelino', 'Meninas, tudo bem?'),
              l('kelly', 'O João chegou super preocupado com você, Camila.'),
              l('avelino', 'Senta aí direitinho, vamos cuidar de vocês!'),
              l('emanuel', 'A Lorena também passou mal.'),
              l('kelly', 'Nossa!!'),
              l('lorena', 'Mas já estou bem, bem e calma!'),
              l('emanuel', 'Eitaaaa!!!!'),
              l('todos', 'O que foi Emanuel?'),
              l('emanuel', 'Cadê o Teddy? Aaaaai, Teddy, você me deixou!'),
              s('Entra João sem fôlego.'),
              l('joao', 'Ai, tô morto! Quase que acompanho vocês Avelino e Kelly.'),
              l('lorena', 'ANHAM, SEI!'),
              l('emanuel', 'Ah meu Deus! Cadê Teddy!'),
              l('nina', 'Calma, Emonoel, vamos achar!'),
              l('joao', 'Aqui ele, ó!'),
              l('emanuel', 'Aii, ainda bem que tu voltou, Teddy!'),
              l('avelino', 'Nossa, gente! Estou impressionado como vocês foram bons samaritanos agora.'),
              l('remela', 'Bons o que?'),
              l('kelly', 'Samaritano, Remela! Isso que vocês fizeram uns pelos outros nos fez lembrar uma parábola de Jesus.'),
              l('avelino', 'Sentem aí e escutem essa história: Certa vez estava Jesus conversando, quando um doutor da Lei, quis pô-lo a prova perguntando:'),
              l('doutor-da-lei', 'Com licença mestre! Posso lhe fazer uma pergunta? O que devo fazer para herdar a vida eterna?'),
              l('jesus', 'Você é doutor?'),
              s('O doutor responde que sim com cabeça.'),
              l('jesus', 'O que diz a lei? Como você a lê?'),
              l('doutor-da-lei', 'A lei diz: ame a Deus de todo o coração, de toda a alma, de todas as forças e de todo entendimento; e também ame ao próximo como a você mesmo.'),
              l('jesus', 'Você respondeu correto. Faça isso e viverá.'),
              l('doutor-da-lei', 'Ah!! Mas quem é o meu próximo?'),
              l('jesus', 'Eu já ouvi. Vocês querem ouvir?'),
              s('Pergunta para as crianças.'),
              l('kelly', 'Jesus contou-lhe a seguinte história: Um dia, um pobre homem descia da cidade de Jerusalém para uma outra cidade, Jericó, a trinta e três quilômetros daquela capital, no Vale do Jordão.'),
              s('Entra o homem. Uma pequena pausa.'),
              l('kelly', 'A estrada era cheia de curvas. Nela havia muitos penhascos, em cujas grutas era comum se refugiarem, os salteadores de estradas, que naquele tempo eram muito perigosos.'),
            ],
          },
        ],
      },
      {
        title: '2ª PARTE — A parábola',
        scenes: [
          {
            title: 'O assalto, o Sacerdote, o Levita e o Samaritano',
            setting: 'Abre cortina e inicia a cena por trás dos adolescentes.',
            beats: [
              l('ladrao-1', 'Bate nele! Bate!!!'),
              l('ladrao-2', 'Ele não está se mexendo.'),
              l('ladrao-1', 'Veja o que ele tem.'),
              s('O ladrão abre as sacolas e não acha nada.'),
              l('ladrao-2', 'Não tem nada.'),
              l('ladrao-1', 'Não pode ser, deve ter uma sacolinha amarrada no pescoço.'),
              s('Tira a sacola do pescoço.'),
              l('ladrao-1', 'Eu sabia, agora vamos antes que apareça alguém.'),
              l('avelino', 'Logo depois do criminoso assalto, passou por aquele mesmo lugar um sacerdote do templo de Salomão. Esse sacerdote vinha de Jerusalém, onde possivelmente terminara seus serviços religiosos, e se dirigia também para Jericó.'),
              s('Entra o sacerdote, vê o pobre viajante caído na estrada, ferido, meio morto gemendo.'),
              l('sacerdote', 'Pobre homem!!! Se eu não estivesse a serviço de Deus eu teria tempo de parar. Ó Deus, por favor, ajude este pobre infeliz.'),
              l('homem', 'Ajude-me, por favor.'),
              l('kelly', 'Instantes depois, passa também pelo mesmo lugar um levita. Os levitas eram auxiliares do culto religioso do Templo.'),
              l('levita', 'Você foi ASSALTADO? Isto quer dizer que por aqui há ladrões?! EU SOU LEVIIITA, EU NÃO TENHO DINHEIIIIIRO!!! Perdoe-me, mas começo a perceber que não é seguro por aqui.'),
              l('homem', 'Ó Deus tenha misericórdia.'),
              l('avelino', 'Uma terceira pessoa passa pelo mesmo lugar. Era um samaritano, que igualmente vinha de Jerusalém.'),
              s('O samaritano fica para socorrer.'),
              l('samaritano', 'Ainda está respirando, tá vivo. Parece muito ferido.'),
              s('Rasga as vestes e faz ataduras no homem.'),
              l('homem', 'Obrigado senhor. Obrigado por ter parado.'),
              l('samaritano', 'Tome, beba isto aqui.'),
              l('homem', 'Ladrões, eles vão voltar.'),
              l('samaritano', 'Você tem razão, eles podem voltar, por isso tenho que levar você para Jericó.'),
              s('Os dois saem andando para trás das cortinas.'),
              l('kelly', 'O samaritano conduziu-o para estalagem próxima e cuidou dele com zelo durante toda a noite. Na manhã seguinte, tendo de continuar sua viagem, chamou a dona do pequeno hotel.'),
              s('Entram em cena o samaritano e a dona da estalagem.'),
              l('samaritano', 'Aqui estão o dinheiro das minhas despesas e aqui o pagamento da comida e da cama daquele homem até ele melhorar. E se não for bastante eu lhe pagarei o resto quando voltar.'),
              l('dona-estalagem', 'Obrigada senhor! Muito bonito isso que você fez por este homem, mesmo ele sendo um desconhecido. Já hospedei muita gente nesta estalagem e nunca vi um homem de tão bom coração como o senhor. Admiro muito sua atitude. Vá em paz, senhor que eu cuidarei desse pobre homem.'),
              l('samaritano', 'Só fiz o que qualquer um faria. Que a paz esteja com você!'),
              s('Sai de cena. A cortina se abre e Jesus continua… Fecham as cortinas.'),
            ],
          },
          {
            title: 'A conclusão',
            setting: 'De volta à roda dos adolescentes.',
            beats: [
              l('avelino', 'Pois bem jovens, quem foi que se aproximou do homem atacado pelos ladrões?'),
              l('remela', 'Foi o Sa… Sam… Foi o que usou de misericórdia para com ele.'),
              l('avelino', 'Foi o Samaritano Remela. E Jesus os disse, "Vá e faça o mesmo. Aí você também herdará a vida eterna".'),
              l('camila', 'AAH, agora eu entendi! Quando eu machuquei meu pé a Lorena e João logo se preocuparam comigo e logo apareceu o Eugênio, o Emanuel e cada um tentou ajudar de uma forma, por mais que eles não tivessem a força, mas eles tentaram, mas aí veio as meninas e também se preocuparam comigo e a Lorena. E então veio o Remela e pode levantar a Lorena e se preocupou no bem-estar da gente. Eu não me senti sozinha nenhum minuto, por mais que foi simples, eu só torci o pé, mas vocês não me deixaram, ficaram comigo.'),
              l('kelly', 'E a gente pode fazer muito mais, podemos ajudar em nossa casa, na escola, na rua só não podemos passar pelas pessoas e não ajudá-las, não podemos ser iguais ao Sacerdote e o Levita, temos que ser samaritanos.'),
              l('todos', 'IMITEM O BOM SAMARITANO! VÁ E FAÇA O MESMO!'),
            ],
          },
        ],
      },
    ],
  },

  // =========================================================================
  // 3ª PEÇA
  // =========================================================================
  {
    id: '3',
    slug: 'amigos-de-jesus',
    number: '3ª Peça',
    title: 'Cenas Relâmpago — Amigos de Jesus',
    synopsis: 'Cenas curtas em que Juju sente a casa vazia, os adolescentes descobrem amizades novas e Jesus mostra o valor da amizade através da história de Marta, Maria e Lázaro.',
    parts: [
      {
        title: '1ª PARTE — Juju sozinha e as novas amizades',
        scenes: [
          {
            title: 'Juju e Salete',
            setting: 'Abrem as cortinas e aparece a boneca Juju na cama falando de como está bom o final de semana, de que está aproveitando a cama, o quarto…',
            beats: [
              l('juju', 'É… até que não tá tão ruim esse final de semana sem a Camila. Com um quarto só pra mim, uma cama pra mim… aiai… passaria o ano todo assim!'),
              s('Salete entra no quarto e Juju entra para debaixo da cama.'),
              l('salete', 'Aaai que saudades da minha filhinha! Desde que ela foi embora, eu passei a escutar vozes nessa casa.'),
              l('juju', 'Tava bom demais para ser verdade…'),
              l('salete', 'Pera, escutei novamente uma vez… tem alguém aí?'),
              l('juju', 'Miau!'),
              l('salete', 'Tem alguém aíí??'),
              l('juju', 'MIAAAU!'),
              l('salete', 'TEM ALGUÉM AÍ??'),
              l('juju', 'É O GATO!!'),
              s('Fecham as cortinas. Entram os adolescentes em grupos diferentes se interagindo cada um de seu jeito e falando da importância de conhecer novos amigos, de não ficar sempre com os mesmos grupos, de que cada um pode ajudar o outro de uma forma diferente.'),
            ],
          },
          {
            title: 'Novas amizades',
            setting: 'Entram juntos na sequência: Emanuel e Camila.',
            beats: [
              l('camila', 'Sabe, Emanuel? Eu acho tão lindo isso de você levar o Teddy para onde quer que você vá.'),
              l('emanuel', 'O Teddy é meu melhor amigo, Camila. Ele sabe de tudo que acontece na minha vida. Sem o Teddy eu fico tliste…tlistinho.'),
              l('camila', 'Own! Eu também tenho um brinquedo que é o meu melhor amigo! É uma boneca, é a Juju! Tô com tantas saudades dela!'),
              l('emanuel', 'Own! Tem alguns bliquedinhos que são tão importantes em nossas vidas, né? Apesar de já sermos adolescentes, não podemos nos envergonhar deles e esquecê-los. Eles foram muito importantes para nos tornar o que somos hoje.'),
              l('camila', 'Que lindo isso, Emanuel! É isso mesmo! Nossos brinquedos é uma das formas de revivermos nossa infância e não deixarmos a alegria de criança ser tirada de nós.'),
              s('Camila e Emanuel se sentam no banco e vai entrando em cena Eugênio, Nina e Britney.'),
              l('britney', 'Migo, seu loko! Você bem que poderia me ensinar a fórmula de bhaskara esses dias, né?'),
              l('eugenio', 'Claro que ensino! Mas somente com um fato condicional HEHEHE'),
              l('britney', 'Qual, migo?'),
              l('eugenio', 'Se você me der algumas dicas de moda. Tudo bem que eu nem preciso, já sou bastante fooor…midável. Mas eu quero me tornar aquele ícone da música popular brasileira, o EUGÊNIO SAFADÃO! HEHEHE'),
              l('britney', 'Migo, seu loooko! Vai ter um look lacrador!'),
              s('Britney nota Nina um pouco mais atrás calculando os seus passos e pergunta.'),
              l('britney', 'MIGAAA, SUA LOKAA! SEJA MENOS ATRASADA! Tá fazendo o quê aí?'),
              l('nina', 'Ain, miga! Tô calculando quantos passos devo dar pra chegar até o banco.'),
              l('britney', 'Miga, isso é coisa do Eugênio!'),
              l('nina', 'Eu sei… SOMOS TODOS EUGÊNIO SAFADÃO!'),
              s('Eugênio, Britney e Nina se sentam e em seguida entra Remela e João.'),
              l('joao', 'Curti aquela tua dancinha… Como é mesmo? Tá traan..qui…lo… tá favoráá…vel… Tá tran…qui…lo… Tá…favorááá….vel.'),
              l('remela', 'Brooooother, nossa parceria vai permanecer depois do EAC, CER-TE-ZA! O Remelinha aqui não vai deixar você dormir no ponto!'),
              l('joao', 'O quê? Dormir? Quero!'),
              s('Entra em seguida Paty e Lorena.'),
              l('paty', 'Estou tão feliz aqui no EAC, antes eu só queria saber das minhas migas, mas agora eu aprendi a me abrir para novas amizades.'),
              l('lorena', 'Eu tava sempre apressada e não reparava nos outros ao meu redor, mas estou mudando isso de ser tão agoniada… Ops, quase!'),
              l('paty', 'É, nós temos mesmo muito que aprender com nossas diferenças… Tipo, agora já gosto de suas meias, retrô é a nova moda!'),
              s('Logo após todos entrarem e se sentarem no banco embaixo do palco, entram os coordenadores e sentam juntos com eles. Fecha cortina.'),
              l('avelino', 'Olá, galerinha, como estão se sentindo? Estão gostando?'),
              l('joao', 'Tá bem legal, tô curtindo muito!'),
              l('eugenio', 'Por incrível que pareça eu ainda não senti saudades de estudar!'),
              l('kelly', 'Que legal, meninos! Eu tô vendo que até o Teddy está gostando, não é Emanuel?'),
              l('emanuel', 'Ah, Kelly, Teddy se interage muito rápido, ele gosta de fazer amizades, ele é meu melhor amigo!'),
              l('avelino', 'Ah, vocês sabiam que Jesus também é deste jeitinho assim.'),
              l('remela', 'Desse jeitinho? Que nem o Teddy? Com pelos? Pois lá em casa as fotos de Jesus ele não é assim não!'),
              l('paty', 'Remelaaaa, stop!!!'),
              l('britney', 'Remelaaaa, stop!!!'),
              l('avelino', 'Não, Remela, ele é amigo assim igual ao Teddy, melhor ainda.'),
              l('kelly', 'Jesus ele ama muito os seus amigos e ele nunca abandona nenhum deles, e ele quer que nós sejamos amigos dele também, só precisa que nos aproximemos dele.'),
              l('nina', 'Como vocês sabem que Jesus ama tanto seus amigos?'),
              l('avelino', 'Vou contar uma historinha pra vocês de uns dos amigos de Jesus, agora eu preciso que vocês usem a imaginação de vocês, pode ser?'),
              l('todos', 'Pode!!!'),
              l('kelly', 'Niinaaa? Pode ser?'),
              l('nina', 'Pode! Pode!'),
              s('Abre cortina.'),
            ],
          },
          {
            title: 'Marta e Maria recebem Jesus',
            setting: 'Casa de Marta, Maria e Lázaro em Betânia.',
            beats: [
              l('avelino', 'Pois imagina essa cena, Nina… Um dia Jesus estava a viajar pela Terra Santa, como sempre costumava fazer, Ele queria levar a palavra do Senhor a pessoas que moravam nos lugares mais longínquos. Durante sua peregrinação, Ele resolveu fazer uma parada em uma aldeia chamada Bethânia. Para visitar alguns amigos que ali moravam. Ele se dirigiu a casa dos irmãos, Marta, Maria e Lázaro. Ao chegar Jesus cumprimentou os três e se pôs a falar sobre as maravilhas do Senhor. Lázaro ficou de longe, apenas observando o que Jesus falava, enquanto Marta estava cheia de afazeres com a casa e pouca atenção dava ao Mestre, já Maria sentou-se aos pés de Jesus para ouvi-lo falar:'),
              l('marta', 'O que é que eu sou sem Jesus? Nada! Nada! Nada! Eeeeita casa suja, pense numa poeirada, e engraçado que só eu limpo aqui, mai eu sô mole mermo. Eu aqui limpando, limpando e Maria ali, na boa, sentadinha. Maria, mulher, tu num me ajuda não é???'),
              l('maria', 'Marta, querida! Você não percebe que temos visita, você não ver quem está em nossa casa?'),
              l('marta', 'As visitas chegando e a sujeira tomando conta, né?'),
              l('kelly', 'Marta ficava doidinha porque tinha muito serviço e Maria nem olhava para ela. Aí Marta resolveu questionar Jesus para ele pôr Maria pra ajudar ela também.'),
              l('marta', 'Ow, Senhor não te importas que Maria me deixe sozinha para servi-lo e para cuidar da casa? Diga aí a ela que me ajude!'),
              l('jesus', 'Marta, Marta, se acalme, mulher, você anda muito inquieta e se preocupando com muitas coisas, quando só uma é importante. A vida é passageira, minha amiga. Olhe, tua irmã, Maria, soube com o que se preocupar.'),
              s('Fecha cortina.'),
            ],
          },
        ],
      },
      {
        title: '2ª PARTE — A notícia sobre Lázaro',
        scenes: [
          {
            title: 'O mensageiro e os discípulos',
            setting: 'Abre cortina.',
            beats: [
              l('avelino', 'Aí, outro dia, estava Jesus reunido assim como a gente, com seus amigos, quando um mensageiro veio de Bethânia trazendo notícias alarmantes para Ele.'),
              l('mensageiro', 'CORREIO, CORREIO!!!!! Trago uma mensagem para o Senhor Jesus Cristo!!!'),
              l('jesus', 'Aqui estou!'),
              l('mensageiro', 'Senhor, eu trago notícias de suas amigas, Marta e Maria. O irmão delas, Lázaro, está muito doente e elas pedem por sua ajuda para salvá-lo.'),
              l('jesus', 'Diga a elas que não se preocupem, que essa doença não terminará em morte, mas mostrará a Glória de Deus e glorificará o filho de Deus, irei assim que possível.'),
              l('avelino', 'Só que os amigos do Senhor, que são os discípulos, ficaram muito preocupados quando o senhor disse que iria aonde elas estavam, pois Jesus ia correr muito risco indo até a cidade delas.'),
              l('tome', 'Senhor, Bethânia é perto de Jerusalém e lá com certeza seus inimigos irão pegá-lo.'),
              l('joao-discipulo', 'Uma viagem para Bethânia agora, seria como entrar numa caverna de lobos famintos.'),
              l('pedro', 'Sabemos que todos gostamos de Lázaro, mais é muito arriscado viajar para Bethânia agora.'),
              l('jesus', 'Não iremos, não agora.'),
              s('Congela cena.'),
              l('avelino', 'Aí se passaram dois dias e Jesus decidiu ir, mas os discípulos se assustaram novamente.'),
              l('jesus', 'Vamos.'),
              l('tome', 'Mestre? Para onde vamos?'),
              l('jesus', 'Para Bethânia.'),
              l('todos', 'Bethânia?'),
              l('joao-discipulo', 'Mas Mestre há alguns dias o Senhor mesmo disse que não iríamos a Bethânia.'),
              l('jesus', 'Nosso amigo Lázaro dorme e eu vou acordá-lo.'),
              l('pedro', 'Ora, se Lázaro apenas dorme, ele está bem!'),
              l('jesus', 'Não, Pedro! Lázaro está morto e preciso ir.'),
              l('tome', 'Eu não entendo, se ele estava doente porque esperamos?'),
              l('jesus', 'Para que a fé de vocês se fortaleça quando eu o acordar da morte.'),
              l('tome', 'Só desgraça nos espera em Bethânia, morreremos todos.'),
              l('jesus', 'Tomé, minha vida é como um dia que nunca tem fim, venham e vamos logo a Bethânia, Lázaro precisa.'),
              s('Fecha cortina.'),
            ],
          },
        ],
      },
      {
        title: '3ª PARTE — A ressurreição de Lázaro',
        scenes: [
          {
            title: 'Marta, Maria e o milagre',
            setting: 'Chegada em Bethânia, quatro dias após a morte de Lázaro.',
            beats: [
              l('avelino', 'Aí, Jesus e os discípulos foram, mas quando Jesus e os discípulos chegaram a Bethânia já faziam quatro dias que Lázaro estava no sepulcro e Marta correu desesperada ao encontro de Jesus.'),
              s('Abre a cortina.'),
              l('marta', 'Ah Mestre, ainda bem que estais aqui, mas agora é tarde, meu irmão está morto. Sei que Deus lhe dará tudo que eu pedir.'),
              l('jesus', 'Marta, Marta, levanta-te e não chore, acredite, Lázaro vai se levantar de novo.'),
              l('marta', 'Sei que se levantará de novo, no dia da ressurreição.'),
              l('jesus', 'Eu sou a Ressureição e a Vida, aquele que acreditar em mim viverá e todos aqueles que vivem e acreditam nisso nunca morrerão. Você acredita nisso, Marta?'),
              l('marta', 'Sim! Eu acredito que és Cristo, filho de Deus, que veio pra nos salvar, perdoando os nossos pecados.'),
              s('Nesse momento Maria entra em cena chorando e abraça Jesus.'),
              l('maria', 'Mestre! Chegastes tarde, nosso irmão morreu já faz quatro dias.'),
              l('avelino', 'Aí os discípulos ficaram sem reação com tudo aquilo que estava acontecendo, mas Jesus pediu pra ver onde Lázaro estava.'),
              l('jesus', 'Venha, Maria, mostre-nos onde colocaram Lázaro, preciso vê-lo.'),
              l('maria', 'Mas Senhor, já cheira mal.'),
              s('Fecha cortina e colocam a caverna em palco.'),
              l('jesus', 'Maria, se você acredita, verá a glória de Deus. Retirem a pedra.'),
              s('Maria entra em cena levando Jesus até o túmulo de Lázaro. Dois discípulos retiram a pedra.'),
              l('jesus', 'Pai, graças te dou porque me ouvistes, bem sei que sempre me ouves, mas te peço isso para que creiam que fui enviado por Ti.'),
              s('Jesus se volta para a porta do sepulcro lentamente.'),
              l('jesus', 'Lázaro, acorde! Deixe a escuridão e venha para fora.'),
              s('Todos se espantam e Lázaro sai do sepulcro. Fecha cortina.'),
            ],
          },
        ],
      },
      {
        title: '4ª PARTE — Reflexão final',
        scenes: [
          {
            title: 'A conversa dos adolescentes',
            beats: [
              l('avelino', 'E Lázaro saiu, Lázaro estava vivo e muitos se maravilharam, creram que Jesus era o filho de Deus vivo, e este é apenas um dos milhares de milagres e sinais e bênçãos que Jesus realizou, que realiza ainda hoje e que sempre irá realizar.'),
              l('kelly', 'É só a gente acreditar, Jesus é nosso amigo e ele não nos deixa na mão.'),
              l('joao', 'Jesus era igualzinho a mim, demorou três dias para chegar à Betânia!'),
              l('eugenio', 'Às vezes o tempo cronológico de Deus não é o mesmo que o nosso.'),
              l('lorena', 'É, quase sempre nós somos muito apressadinhos e queremos que tudo sempre saia do nosso jeito.'),
              l('camila', 'Mas a gente tem que saber esperar, porque Jesus nunca nos abandona, Lorena.'),
              l('emanuel', 'Às vezes estamos tão tlistes, tlistinhos que nossa fé em Deus diminui… Mas não podemos vacilar.'),
              l('paty', 'Ow, migo… Mas é só colocarmos nossas esperanças em Jesus que Ele olha para nós.'),
              l('remela', 'Migos, seus lokos, sejam MENOS REFLEXIVOS!'),
              l('nina', 'Remela, STOP! Eu aprendi muito com essas histórias, Jesus é mesmo nosso amigo.'),
              l('britney', 'Ai, migosss! Que lindo, que prova de amizade!'),
            ],
          },
        ],
      },
      {
        title: '5ª PARTE — É tão lindo',
        scenes: [
          {
            title: 'Juju e a música final',
            setting: 'Abrem-se as cortinas e Juju está em cena.',
            beats: [
              l('juju', 'Vivemos julgando as pessoas pelas roupas que elas vestem, pela aparência de ser um pouco bobão, esquisito ou se são muito inteligentes ou não. Por conta disso, deixamos de fazer novas amizades e aprender coisas novas com o modo diferente de ser de cada um. Um dos maiores tesouros que a gente pode ter é um amigo! Se é amigo, essas diferenças se tornam pequenas. Se é amigo, não preciso mudar. O importante é termos um companheiro verdadeiro ao nosso lado, independentemente de ser parecidos com a gente ou não.'),
              s('Começa a música "É tão lindo" e entram em cena os adolescentes com os coordenadores e se organizam de um lado as meninas e de outro os meninos.'),
              l('meninas', 'Se tem bigodes de foca, nariz de tamanduá…'),
              l('meninos', 'Parece meio estranho, hein?'),
              l('meninas', 'Também bico de pato e um jeitão de sabiá / Mas se é amigo, não precisa mudar…'),
              l('meninos', 'É tão lindo, deixa assim como está…'),
              l('meninas', 'E eu adoro, adoro, difícil é a gente explicar que é tão lindo!'),
              l('meninos', 'Se tem bigodes de foca, nariz de tamanduá… Mas se é amigo de fato, a gente deixa como ele está…'),
              l('todos', 'É tão lindo, não precisa mudar…'),
              l('meninos', 'É tão lindo, deixa assim como está…'),
              l('meninas', 'E eu adoro…'),
              l('meninos', 'É claro / bom mesmo é a gente encontrar… um bom amigo! / São os sonhos verdadeiros, quando existe amor. / Somos grandes companheiros / Os três mosqueteiros…'),
              l('meninas', 'Como eu vi no filme…'),
              s('Entram o restante dos personagens.'),
              l('todos', 'E é tão lindo / não precisa mudar / É tão lindo / Deixa assim como está / E eu adoro, é claro, bom mesmo é a gente encontrar… / Dessa amizade que nasceu…'),
              l('meninas', 'Você e eu…'),
              l('meninos', 'Nós e vocês…'),
              l('todos', 'Vocês e eu… E é tão lindo!'),
            ],
          },
        ],
      },
    ],
  },

  // =========================================================================
  // JÚRI DO BRUNO
  // =========================================================================
  {
    id: '4',
    slug: 'juri-do-bruno',
    number: 'Especial',
    title: 'O Júri de Bruno: culpado ou inocente?',
    synopsis: 'Um julgamento inspirado em Encanto: Bruno é acusado, defendido, testemunhado e a plateia vota — para uma mensagem forte sobre acolhimento e não julgamento.',
    parts: [
      {
        title: '1. ABERTURA',
        scenes: [
          {
            title: 'Entrada do Bruno',
            setting: 'Palco com 7 personagens. Equipe de Som e Projeção inicia o refrão da música tema do filme Encanto: "Não falamos do Bruno, não, não…"',
            beats: [
              l('juiz', 'Que seja iniciado o julgamento. Pode entrar o réu.'),
              s('Durante a música: Bruno entra lentamente, cabeça baixa, postura retraída, reage de forma desconfortável à música (como alguém rejeitado). A música abaixa ou encerra após a entrada.'),
              l('juiz', 'Silêncio no tribunal!'),
              s('Pausa breve.'),
              l('juiz', 'Boa noite, EAC! Hoje temos um caso importante para julgar. Bruno Madrigal… sumiu por anos. A família sofreu. A casa quase caiu. Mas a pergunta é: Ele é culpado… ou só foi mal compreendido? Hoje, vocês vão decidir.'),
            ],
          },
        ],
      },
      {
        title: '2. ACUSAÇÃO',
        scenes: [
          {
            title: 'As falas de acusação',
            beats: [
              l('acusacao-1', 'Bruno é culpado! Ele via coisas ruins e não fazia nada para mudar.'),
              l('acusacao-2', 'Ele desapareceu! Deixou a família sofrendo, com medo e sem respostas.'),
              l('acusacao-1', 'Quem ama não some. Quem ama fica e enfrenta junto.'),
            ],
          },
        ],
      },
      {
        title: '3. DEFESA',
        scenes: [
          {
            title: 'As falas de defesa',
            beats: [
              l('defesa-1', 'Inocente! Bruno não foi embora… ele ficou escondido dentro da própria casa.'),
              l('defesa-2', 'Ele abriu mão da própria vida para proteger quem ele amava.'),
              l('defesa-1', 'Ele vivia sozinho, em silêncio, comendo restos… só para continuar perto da família.'),
              l('defesa-2', 'Isso não é abandono. Isso é amor… mesmo sendo rejeitado.'),
            ],
          },
        ],
      },
      {
        title: '4. TESTEMUNHO',
        scenes: [
          {
            title: 'Mirabel testemunha',
            beats: [
              l('mirabel', 'Eu vi onde ele vivia… não era conforto, era solidão. Ele não era o problema… ele era alguém que ninguém quis entender. Quantas vezes a gente afasta alguém só porque é diferente?'),
            ],
          },
        ],
      },
      {
        title: '5. INTERAÇÃO',
        scenes: [
          {
            title: 'Antes da votação',
            beats: [
              l('juiz', 'Agora conversa rapidinho com quem está do seu lado: Bruno é culpado ou inocente?'),
            ],
          },
        ],
      },
      {
        title: '6. VOTAÇÃO',
        scenes: [
          {
            title: 'Com movimento',
            beats: [
              l('juiz', 'Agora é com vocês, EAC! Quem acha que o Bruno é INOCENTE, fica de pé!'),
              s('Aguarda e observa.'),
              l('juiz', 'Agora… Quem acha que ele é CULPADO, permanece sentado!'),
              s('Aguarda e observa.'),
            ],
          },
        ],
      },
      {
        title: '7. FECHAMENTO',
        scenes: [
          {
            title: 'Forte e direto',
            setting: 'Juiz pede silêncio, muda o tom.',
            beats: [
              l('juiz', 'Agora presta atenção… O Bruno não é só um personagem.'),
              l('juiz', 'Existe um "Bruno" na sua escola. Aquele que todo mundo evita.'),
              l('juiz', 'Existe um "Bruno" na sua família. Aquele que ninguém quer entender.'),
              l('juiz', 'E talvez… exista um "Bruno" dentro de você. Quando você se sente rejeitado, sozinho ou incompreendido.'),
              l('juiz', 'A gente julga rápido. Afasta fácil. E esquece de amar.'),
              l('juiz', 'Jesus nos ensina uma coisa muito clara: não julgar… e amar de verdade.'),
              l('juiz', 'Hoje, eu te faço uma pergunta: Quem você tem afastado da sua vida? Quem você precisa acolher de volta?'),
              l('juiz', 'Não seja mais um a apontar o dedo. Seja aquele que estende a mão. Porque, no final… foi o amor que trouxe o Bruno de volta para casa.'),
              s('Orientações para a equipe: Bruno deve reagir com expressões (tristeza, medo, isolamento). Juiz precisa conduzir com firmeza, principalmente no fechamento. Evitar exageros de humor, manter leve, mas com propósito. Alinhar previamente com a equipe de Som e Projeção o tempo da música na entrada do Bruno.'),
            ],
          },
        ],
      },
    ],
  },
];

// Expõe globalmente para o app.js
window.CHARACTERS = CHARACTERS;
window.PLAYS = PLAYS;
